# Generated by Django 4.2.1 on 2024-06-17 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="activate_code",
            field=models.CharField(
                blank=True, max_length=6, null=True, verbose_name="инвайт код пригласившего пользователя"
            ),
        ),
    ]
